# Generated by Django 3.2.3 on 2022-08-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default=' ', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('stipend', models.FloatField(default=0.0)),
                ('img', models.ImageField(upload_to='pics')),
                ('date', models.DateField()),
                ('duration', models.DurationField()),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
