# Generated by Django 3.2.3 on 2022-08-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='duration',
        ),
    ]
