# Generated by Django 3.2.3 on 2022-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_remove_internship_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='duration',
            field=models.IntegerField(default=6),
        ),
    ]
