# Generated by Django 3.2.3 on 2022-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0003_internship_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phno', models.IntegerField(max_length=10)),
                ('tell_me', models.TextField()),
                ('address', models.TextField()),
                ('address2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('zip', models.IntegerField(max_length=6)),
            ],
        ),
    ]
