# Generated by Django 3.2.3 on 2022-09-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0004_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.IntegerField(),
        ),
    ]
