# Generated by Django 3.2.3 on 2022-09-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0005_auto_20220906_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phno',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='contact',
            name='zip',
            field=models.CharField(default=0, max_length=6),
        ),
    ]
