# Generated by Django 3.2.3 on 2022-09-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_alter_resume_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='date',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='user',
        ),
    ]
